# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16J9jUTo7Vbi9XtAI3I0_0UzZjEvfHoIG
"""

import math

# Noktaların tanımlanması (2D uzayında)
points = [(1, 2), (4, 6), (7, 8), (2, 1), (5, 3)]

# Öklid mesafesini hesaplayan fonksiyon
def euclideanDistance(point1, point2):
    return math.sqrt((point2[0] - point1[0])**2 + (point2[1] - point1[1])**2)

# Mesafeleri saklamak için bir liste
distances = []

# Her nokta çifti arasındaki mesafeleri hesaplama
for i in range(len(points)):
    for j in range(i + 1, len(points)):
        distance = euclideanDistance(points[i], points[j])
        distances.append(distance)

# Minimum mesafenin bulunması ve yazdırılması
min_distance = min(distances)
print(f"Minimum Öklid mesafesi: {min_distance}")